import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { servicePages } from '../src/data.js';

await mkdir('artifacts', {recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page = await context.newPage();
const origin='http://127.0.0.1:5173';
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(origin))errors.push(`${r.status()} ${r.url()}`);});
let passed=0;
const check=(name,condition)=>{assert.ok(condition,name);passed++;console.log(`PASS ${name}`);};
try {
  await page.goto(origin);
  await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:'artifacts/home-desktop.jpg',type:'jpeg',quality:75});
  await page.screenshot({path:'artifacts/home-full.jpg',type:'jpeg',quality:65,fullPage:true});
  for(const route of ['/','/work','/work/after-dark','/design','/production','/rentals','/about','/services',...servicePages.map(service=>`/services/${service.slug}`)]){
    await page.goto(`${origin}/#${route}`);
    await page.locator('h1').waitFor();
    await page.evaluate(async()=>{await document.fonts.ready;document.querySelectorAll('img').forEach(img=>img.loading='eager');await Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=r;img.onerror=r;})));});
    check(`Desktop route ${route} has no overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    check(`Images on ${route} loaded`,await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.naturalWidth>0)));
  }
  await page.goto(`${origin}/#/services`);
  check('Services overview lists all 13 service destinations',await page.locator('.service-catalog-card').count()===13&&await page.locator('.service-catalog-card').evaluateAll(cards=>cards.every(card=>card.getAttribute('href')?.startsWith('#/services/'))));
  for(const service of servicePages){
    await page.goto(`${origin}/#/services/${service.slug}`);
    check(`${service.title} uses its SEO title`,await page.title()===service.seoTitle);
    check(`${service.title} has all scope details`,await page.locator('.service-scope-list li').count()===service.details.length);
  }
  await page.goto(`${origin}/#/production`);
  check('Production page lists each detailed service',await page.locator('.service-detail').count()>=11);
  check('Audio visual and event branding services are visible',await page.getByRole('heading',{name:'Audio Visual (AV) Systems'}).isVisible()&&await page.getByRole('heading',{name:'Event Branding & Signage'}).isVisible());
  await page.locator('.service-detail .button').first().click();
  check('Service quote opens the existing project brief',await page.locator('.project-dialog').isVisible());
  await page.keyboard.press('Escape');
  await page.goto(`${origin}/#/about`);
  check('About page identifies the CEO without placeholder wording',await page.getByRole('heading',{name:'TENYWA MUSA'}).isVisible()&&await page.getByRole('img',{name:'Tenywa Musa monogram'}).isVisible());
  const [profileDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:/COMPANY PROFILE PDF/}).click()]);
  check('Company profile downloads as a PDF',profileDownload.suggestedFilename()==='tm-concepts-company-profile.pdf'&&await page.getByText('PROFILE DOWNLOADED',{exact:true}).isVisible());
  check('About page includes the supplied story and mission',await page.getByRole('heading',{name:/BUILDING EXPERIENCES/}).isVisible()&&await page.getByRole('heading',{name:/TURNING IDEAS/}).isVisible());
  check('About page ends with project and direct-contact actions',await page.getByRole('heading',{name:/LET’S DESIGN/}).isVisible()&&await page.getByRole('button',{name:/START A PROJECT/}).last().isVisible()&&await page.getByRole('link',{name:/TALK TO TM CONCEPTS/}).isVisible());
  await page.goto(`${origin}/#/work`);
  check('Portfolio has category filters and project total',await page.getByRole('group',{name:'Filter portfolio by category'}).isVisible()&&await page.locator('.portfolio-count').textContent().then(text=>text.includes('PROJECTS')));
  check('Portfolio offers requested categories',await Promise.all(['Conferences','Corporate','Concerts','Weddings','Nightlife','3D Concepts','Concept → Reality'].map(label=>page.getByRole('button',{name:label,exact:true}).isVisible())).then(values=>values.every(Boolean)));
  await page.getByRole('button',{name:'Concept → Reality',exact:true}).click();
  check('Concept-to-reality filter identifies concept-only work',await page.getByText('Current portfolio entries are concept studies, not records of completed commissions.').isVisible());
  await page.goto(`${origin}/#/rentals`);
  check('Rental catalog includes expanded furniture',await page.locator('.equipment-card').count()>=14&&await page.getByRole('heading',{name:'Modular lounge sofa'}).isVisible()&&await page.getByRole('heading',{name:'Event dining chair'}).isVisible());
  await page.goto(`${origin}/#/rentals`);
  await page.getByRole('searchbox',{name:'Search equipment'}).fill('moving');
  check('Equipment search filters correctly',await page.locator('.equipment-card').count()===1);
  await page.getByRole('button',{name:'View Moving head beam details',exact:true}).click();
  check('Equipment details open',await page.locator('.equipment-dialog').isVisible());
  await page.getByRole('button',{name:'ADD TO YOUR BRIEF',exact:true}).click();
  await page.getByRole('button',{name:'YOUR BRIEF (1)',exact:true}).click();
  const form=page.locator('.project-dialog');
  await form.getByLabel('Venue or location').fill('Kampala Conference Centre');
  await form.getByRole('button',{name:'Continue',exact:true}).click();
  check('An event type is required',await form.getByRole('alert').textContent()==='Choose an event type to continue.');
  await form.getByRole('button',{name:'Conference',exact:true}).click();
  await form.getByLabel('Number of guests').fill('350');
  await form.getByRole('button',{name:'Continue',exact:true}).click();
  await form.getByRole('button',{name:'3D Design',exact:true}).click();
  await form.getByRole('button',{name:'Lighting',exact:true}).click();
  await form.getByRole('button',{name:'Increase Moving head beam quantity'}).click();
  await form.locator('input[type=file]').setInputFiles({name:'venue-plan.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nTest fixture')});
  await form.getByRole('button',{name:'Continue',exact:true}).click();
  await form.getByRole('button',{name:'Review your brief',exact:true}).click();
  check('Contact fields are required',await form.getByRole('heading',{name:'Who’s behind the vision?'}).isVisible());
  await form.getByLabel('Your name').fill('Test Visitor');
  await form.getByLabel('Email').fill('visitor@example.com');
  await form.getByLabel('Phone',{exact:true}).fill('+256700000000');
  await form.getByLabel('Anything else').fill('A conference with a keynote stage.');
  await form.getByRole('button',{name:'Review your brief',exact:true}).click();
  check('Brief review opens',await form.getByRole('heading',{name:'A vision worth building.'}).isVisible());
  const url=new URL(await form.getByRole('link',{name:'Open brief in WhatsApp'}).getAttribute('href'));
  check('WhatsApp targets the supplied Uganda number',url.origin+url.pathname==='https://wa.me/256704282211');
  const brief=url.searchParams.get('text');
  for(const value of ['Conference','Kampala Conference Centre','350','3D Design, Lighting','Moving head beam × 2','visitor@example.com','venue-plan.pdf'])check(`Brief includes ${value}`,brief.includes(value));
  const downloading=page.waitForEvent('download');
  await form.getByRole('button',{name:'Download brief'}).click();
  check('Brief downloads', (await downloading).suggestedFilename()==='TM-Concepts-event-brief.txt');
  await page.screenshot({path:'artifacts/brief-desktop.jpg',type:'jpeg',quality:75});
  await form.getByRole('button',{name:'Back',exact:true}).click();
  check('Back preserves data',await form.getByLabel('Your name').inputValue()==='Test Visitor');
  await page.keyboard.press('Escape');
  check('Escape closes the builder',!await form.isVisible());
  await page.goto(`${origin}/#/design`);
  const comparison=page.getByRole('slider',{name:'Compare wireframe and lighting concept'});
  await comparison.fill('75');
  check('Comparison slider updates',await comparison.getAttribute('aria-valuetext')==='75% wireframe visible');
  await page.getByRole('tab',{name:'03 Visualise'}).click();
  check('Process tab changes scene',(await page.getByRole('tabpanel').textContent()).includes('See the whole picture. Before the first build.'));
  await page.getByRole('tab',{name:'03 Visualise'}).press('ArrowRight');
  check('Process tabs support arrow keys',await page.getByRole('tab',{name:'04 Engineer'}).getAttribute('aria-selected')==='true');
  await page.getByRole('slider',{name:'Rotate the illustrated stage concept'}).fill('12');
  check('Perspective control rotates scene',(await page.locator('.angle-control').textContent()).includes('12°'));
  await page.goto(`${origin}/#/work`);
  await page.getByRole('button',{name:'Nightlife',exact:true}).click();
  check('Portfolio category filters work',await page.locator('.project-card').count()===2);
  await page.goto(`${origin}/#/`);
  await page.getByRole('button',{name:'Explore the TM Concepts production vision'}).click();
  const vision=page.locator('.vision-dialog');
  await vision.getByRole('button',{name:'05 Produce'}).click();
  check('Vision chapters switch',(await vision.textContent()).includes('From a shared vision to a shared experience.'));
  await vision.getByRole('button',{name:'Play concept sequence'}).click();
  check('Vision playback starts',await vision.getByRole('button',{name:'Pause concept sequence'}).isVisible());
  await vision.getByRole('button',{name:'Close vision'}).click();
  const audits=[];
  audits.push({page:'home-desktop',...(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze())});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/home-mobile.jpg',type:'jpeg',quality:75});
  for(const route of ['/','/work','/design','/production','/rentals','/about','/work/after-dark','/services',...servicePages.map(service=>`/services/${service.slug}`)]){
    await page.goto(`${origin}/#${route}`);
    await page.locator('h1').waitFor();
    check(`Mobile ${route} has no overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  }
  await page.getByRole('button',{name:'Open navigation menu'}).click();
  const menu=page.getByRole('dialog',{name:'Site navigation'});
  check('Mobile menu opens',await menu.isVisible());
  await menu.getByRole('link',{name:'05 Rentals',exact:true}).click();
  check('Mobile menu navigates and closes',!await menu.isVisible()&&page.url().endsWith('#/rentals'));
  await page.getByRole('button',{name:'START A PROJECT',exact:true}).first().click();
  check('Mobile form has no overflow',await form.evaluate(el=>el.scrollWidth<=el.clientWidth));
  await page.screenshot({path:'artifacts/builder-mobile.jpg',type:'jpeg',quality:75});
  audits.push({page:'builder-mobile',...(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze())});
  const violations=audits.flatMap(a=>a.violations.map(v=>({page:a.page,id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})));
  await writeFile('artifacts/accessibility.json',JSON.stringify(violations,null,2));
  await writeFile('artifacts/verification.json',JSON.stringify({passed,errors,violations},null,2));
  check('No browser errors or failed assets',errors.length===0);
  console.log(JSON.stringify({checks:passed,errors,accessibility:violations},null,2));
  check('Accessibility audits passed',violations.length===0);
} catch(error) {
  await page.screenshot({path:'artifacts/failure.jpg',type:'jpeg',quality:75,fullPage:true});
  console.error(error);
  process.exitCode=1;
} finally { await browser.close(); }


