export const PHONE = '+256704282211';
export const WHATSAPP = 'https://wa.me/256704282211';
export const SITE_URL = 'https://www.tmconceptz.com';
export const ADDRESS = 'Semawata Road, Ntinda, Kampala, Uganda';

// Inspected, client-supplied event photography and video stills.
export const media = {
  dinner: { name: 'corporate-dinner', alt: 'Corporate dinner setup with banquet seating, a stage and three LED presentation screens', width: 640, height: 360 },
  conference: { name: 'conference-presentation', alt: 'Conference stage with presentation screen, panel chairs and a podium', width: 640, height: 360 },
  paediatric: { name: 'paediatric-conference', alt: 'Paediatric conference stage with a branded digital backdrop, panel seating and podium', width: 640, height: 356 },
  awards: { name: 'rotary-awards', alt: 'Award recipients on a white stage in front of the Rotary Muyenga Bukasa LED backdrop', width: 1280, height: 853 },
  presentation: { name: 'rotary-presentation', alt: 'Speaker at a Rotary-branded podium with a gooseneck microphone and LED screen behind him', width: 853, height: 1280, position: '50% 38%' },
  stage: { name: 'rotary-stage', alt: 'Rotary presidential installation with geometric LED panels, stage lighting, a branded podium and white runway', width: 1280, height: 853 },
  installation: { name: 'rotary-installation', alt: 'Guests at the Rotary presidential installation on a white stage with LED screens and lighting', width: 1280, height: 853 },
  celebration: { name: 'rotary-celebration', alt: 'Certificate presentation in front of the Rotary Muyenga Bukasa digital backdrop', width: 1280, height: 853 },
  podium: { name: 'rotary-podium', alt: 'Speaker at a branded podium between two moving-head lights and geometric LED panels', width: 1280, height: 853 },
};

export const servicePages = [
  { slug: 'event-design-3d-visualisation', title: 'Event Design & 3D Visualisation', short: 'Design & Visualisation', group: 'Design', heading: 'SEE IT BEFORE IT HAPPENS.', summary: 'Floor plans, stage concepts, 3D event impressions and walkthroughs.', intro: 'Design before production. We map the space, develop the stage and visualise the complete event so you can make decisions before the build begins.', capabilities: ['Event concepts','Floor plans','Stage concepts','3D event impressions','Venue walkthroughs','Seating layouts','Lighting visualisation','Technical layouts'], useCases: ['Venue planning','Design approvals','Corporate launches','Wedding layouts'], slot: '3D DESIGN', related: ['technical-production','staging-structures','event-lighting'], seoTitle: 'Event Design & 3D Visualisation Kampala | TM Concepts' },
  { slug: 'technical-production', title: 'Technical Production', short: 'Technical Production', group: 'Production', heading: 'ONE PLAN. EVERY MOVING PART.', summary: 'Technical planning, production management, crew and show execution.', intro: 'We bring the stage, sound, screens, lighting, power and crew into one production plan. From load-in to the final cue, each system has a place and each team knows the sequence.', capabilities: ['Technical planning','Production management','Crew coordination','Build schedules','Show flow and cueing','Technical rehearsals','On-site operation','Load-in and breakdown'], useCases: ['Corporate events','Live performances','Outdoor productions','Special productions'], photo: 'stage', related: ['power-solutions','staging-structures','audio-systems'], seoTitle: 'Technical Event Production Kampala Uganda | TM Concepts' },
  { slug: 'audio-visual', title: 'Audio Visual', short: 'Audio Visual', group: 'Technology', heading: 'AUDIO VISUAL', summary: 'Presentation systems, projection, screens and event technology.', intro: 'Integrated visual and presentation technology for conferences, corporate events and live productions. We plan the content, displays and control position around the room and the programme.', capabilities: ['Presentation Systems','Display Systems','Video Playback','Projection','Conference AV','Technical Operation'], scope: ['Laptops, presentation switching and confidence monitors.','LED walls and presentation screens sized for the audience.','Playback preparation, content checks and show cueing.','Projectors, screens and sightline planning.','Speaker support, panel presentations and control desks.','Technicians coordinating content and displays throughout the show.'], useCases: ['Conferences','Product launches','Panel discussions','Corporate presentations'], photo: 'podium', related: ['led-screens','audio-systems','conference-production'], seoTitle: 'Audio Visual Services Kampala Uganda | TM Concepts' },
  { slug: 'audio-systems', title: 'Audio Systems', short: 'Sound Systems', group: 'Technology', heading: 'SOUND THAT REACHES EVERY SEAT.', summary: 'PA systems, line arrays, microphones, mixers and live audio.', intro: 'Clear speech. Balanced music. Consistent coverage. We plan sound around your audience, venue and programme, then coordinate microphones, mixing and monitoring for the show.', capabilities: ['Concert sound','Conference audio','PA systems and line arrays','Wireless microphones','Mixing consoles','Stage monitoring','DJ audio','Live sound engineering'], useCases: ['Conferences','Concerts','Wedding speeches','DJ performances'], slot: 'AUDIO SYSTEMS', related: ['audio-visual','event-lighting','power-solutions'], seoTitle: 'Sound System Rental Kampala Uganda | TM Concepts' },
  { slug: 'led-screens', title: 'LED Screens', short: 'LED Screens', group: 'Technology', heading: 'BIGGER CANVAS. STRONGER MESSAGE.', summary: 'Indoor and outdoor LED walls and digital displays.', intro: 'Give presentations, live video and brand content room to work. We configure LED displays around viewing distance, the stage design and the conditions at your venue.', capabilities: ['Indoor LED','Outdoor LED','Stage backdrop screens','Side screens','Corporate presentation screens','Digital branding','Video playback','Technical support'], useCases: ['Corporate presentations','Concert backdrops','Brand activations','Outdoor events'], photo: 'installation', related: ['audio-visual','trussing-rigging','power-solutions'], seoTitle: 'LED Screen Rental Kampala Uganda | TM Concepts' },
  { slug: 'event-lighting', title: 'Event Lighting', short: 'Lighting', group: 'Technology', heading: 'LIGHT CHANGES THE EXPERIENCE.', summary: 'Stage lighting, intelligent fixtures and event atmosphere.', intro: 'Show the speaker. Shape the room. Build the atmosphere. Lighting is designed around what needs to be seen and how the event should feel, from the first arrival to the last cue.', capabilities: ['Stage lighting','Moving heads','Architectural lighting','Atmospheric lighting','Corporate lighting','Concert lighting','Wedding lighting','Nightlife lighting'], useCases: ['Stage performances','Corporate dinners','Weddings','Nightlife'], photo: 'podium', related: ['trussing-rigging','power-solutions','technical-production'], seoTitle: 'Event Lighting Hire Kampala Uganda | TM Concepts' },
  { slug: 'power-solutions', title: 'Event Power & Generator Solutions', short: 'Power Solutions', group: 'Technology', heading: 'POWER BEHIND THE PRODUCTION.', summary: 'Generators, backup power and event power distribution.', intro: 'Reliable power is essential for professional events. TM Concepts provides generator supply, backup power and event power-distribution solutions for conferences, concerts, weddings, corporate events and outdoor productions.', capabilities: ['Generator supply','Backup event power','Stage power','LED and AV power','Lighting power','Power distribution','Cable management','Outdoor production support','Technical power planning'], useCases: ['Outdoor productions','Concerts','Wedding venues','Conference backup power'], slot: 'POWER / GENERATOR', related: ['technical-production','led-screens','event-lighting'], seoTitle: 'Generator & Event Power Solutions Kampala | TM Concepts' },
  { slug: 'staging-structures', title: 'Staging & Structures', short: 'Staging & Structures', group: 'Production', heading: 'GIVE THE EVENT ITS STAGE.', summary: 'Stages, platforms, runways and production structures.', intro: 'The stage connects the performer, speaker and audience. We plan platforms, runways and event structures around sightlines, access, the venue and the wider technical build.', capabilities: ['Main stages','Raised platforms','Fashion runways','Podiums','Stage layouts','VIP platforms','Production structures','Installation planning'], useCases: ['Corporate stages','Concerts','Fashion shows','Wedding receptions'], photo: 'stage', related: ['trussing-rigging','technical-production','event-branding-signage'], seoTitle: 'Stage Hire & Event Structures Kampala | TM Concepts' },
  { slug: 'trussing-rigging', title: 'Trussing & Rigging', short: 'Trussing & Rigging', group: 'Production', heading: 'THE STRUCTURE BEHIND THE SHOW.', summary: 'Technical structures supporting lighting, screens and audio.', intro: 'Build the support into the plan. We coordinate truss configurations and rigging requirements with the equipment, venue and production layout before installation.', capabilities: ['Truss layouts','Lighting support','LED screen support','Audio suspension planning','Entrance structures','Technical frames','Venue coordination','Installation planning'], useCases: ['Concert structures','Exhibition spaces','Outdoor stages','Brand entrances'], slot: 'TRUSSING & RIGGING', related: ['staging-structures','event-lighting','led-screens'], seoTitle: 'Trussing & Rigging Services Kampala Uganda | TM Concepts' },
  { slug: 'event-branding-signage', title: 'Event Branding & Signage', short: 'Branding & Signage', group: 'Support', heading: 'MAKE THE BRAND PART OF THE EXPERIENCE.', summary: 'Stage branding, registration areas, media walls and wayfinding.', intro: 'Carry the identity through every part of the event. From the first welcome sign to the stage backdrop, we make graphics, signage and digital content work together.', capabilities: ['Entrance branding','Directional signage','Registration branding','Stage and podium branding','Welcome signage','Media walls','Sponsor branding','Digital signage','Event graphics'], useCases: ['Product launches','Corporate events','Conferences','Brand activations'], photo: 'presentation', related: ['led-screens','conference-production','event-design-3d-visualisation'], seoTitle: 'Event Branding & Signage Kampala Uganda | TM Concepts' },
  { slug: 'event-furniture-rentals', title: 'Furniture & Event Rentals', short: 'Furniture & Rentals', group: 'Support', heading: 'MAKE ROOM FOR YOUR GUESTS.', summary: 'Chairs, tables, sofas, VIP furniture and event accessories.', intro: 'Plan the way people sit, meet and move through the event. We coordinate furniture and rental requirements around your layout, guest numbers and style.', capabilities: ['Function chairs','Dining tables','Cocktail furniture','Lounge furniture','Sofas','VIP seating','Conference furniture','Event accessories'], useCases: ['Conference seating','Wedding receptions','VIP lounges','Corporate dinners'], slot: 'FURNITURE & RENTALS', related: ['event-design-3d-visualisation','conference-production','technical-production'], seoTitle: 'Event Furniture Rental Kampala | TM Concepts' },
  { slug: 'conference-production', title: 'Conference Production', short: 'Conference Production', group: 'Experiences', heading: 'MAKE EVERY PRESENTATION COUNT.', summary: 'Stage, AV, audio, branding and technical support for conferences.', intro: 'Give speakers a clear platform and audiences a clear message. We bring presentation technology, sound, staging, branding and room layouts together for your conference programme.', capabilities: ['Conference stage design','Presentation systems','Microphones and audio','Panel discussions','Confidence monitors','Registration areas','Conference branding','Technical operation'], useCases: ['Summits','Annual meetings','Panel discussions','Corporate conferences'], slot: 'CONFERENCE', related: ['audio-visual','audio-systems','event-branding-signage'], seoTitle: 'Conference Production Kampala Uganda | TM Concepts' },
  { slug: 'concerts-live-events', title: 'Concerts & Live Events', short: 'Concerts & Live Events', group: 'Experiences', heading: 'BUILT FOR THE LIVE MOMENT.', summary: 'Stages, sound, light and screens planned around the performance.', intro: 'A live show needs one coordinated technical plan. We bring together staging, audio, LED, lighting and power around the performers, the audience and the venue.', capabilities: ['Concert staging','Live sound','Performance lighting','LED backdrops','Technical production','Power planning','Show cues','Crew coordination'], useCases: ['Concerts','Festivals','Live performances','Special productions'], slot: 'CONCERT', related: ['audio-systems','event-lighting','power-solutions'], seoTitle: 'Concert & Live Event Production Kampala | TM Concepts' },
  { slug: 'weddings', title: 'Weddings', short: 'Weddings', group: 'Experiences', heading: 'YOUR DAY. THOUGHTFULLY BUILT.', summary: 'Design, staging, lighting, sound and furniture for celebrations.', intro: 'Start with the space and the way you want the day to flow. We bring layouts, stage design, lighting, sound and furniture into a considered wedding production plan.', capabilities: ['Reception concepts','3D visualisation','Wedding stages','Speech and music audio','Atmospheric lighting','LED displays','Guest furniture','Backup power'], useCases: ['Wedding receptions','Introductions','Outdoor celebrations','Private events'], slot: 'WEDDING', related: ['event-design-3d-visualisation','event-furniture-rentals','event-lighting'], seoTitle: 'Wedding Event Production Kampala Uganda | TM Concepts' },
  { slug: 'nightlife', title: 'Nightlife', short: 'Nightlife', group: 'Experiences', heading: 'AFTER DARK. FULL PRODUCTION.', summary: 'DJ audio, lighting and visual systems for nightlife experiences.', intro: 'Plan the sound, lighting and screens around the room, the DJ and the crowd. We coordinate the technical setup for bar activations, club events and evening performances.', capabilities: ['DJ audio','Stage monitoring','Lighting looks','LED content playback','DJ booth displays','Technical operation','Venue planning','Brand activations'], useCases: ['Bar activations','Club events','DJ performances','Nightlife launches'], slot: 'NIGHTLIFE', related: ['audio-systems','led-screens','event-lighting'], seoTitle: 'Nightlife & DJ Event Production Kampala | TM Concepts' },
];
export const services = servicePages;
export const workFilters = ['All','Conferences','Corporate','Concerts','Weddings','Nightlife','LED & AV','Branding','Rentals'];
export const projects = [{
  slug: 'rotary-muyenga-bukasa', title: 'Rotary Muyenga Bukasa', subtitle: 'Presidential installation', location: 'Uganda', category: 'Corporate', categories: ['Corporate','LED & AV','Branding'],
  services: ['Staging','LED screens','Lighting','Podium branding'], images: ['stage','awards','presentation','installation','celebration','podium'],
  description: 'A presidential installation framed by geometric LED panels, a white stage and runway, moving-head lighting and a branded podium.',
  note: 'The stage, podium and presentation areas bring the visual identity into each part of the programme.',
}, {
  slug: 'corporate-dinner', title: 'Corporate Dinner', subtitle: 'A room ready for the programme', location: 'Uganda', category: 'Corporate', categories: ['Corporate','LED & AV','Rentals'],
  services: ['Stage setup','LED displays','Event furniture'], images: ['dinner'],
  description: 'A corporate dinner setup brings banquet seating, a presentation stage and three digital screens into one room.',
  note: 'The screens extend the presentation across the stage while the furniture layout keeps the audience connected to the programme.',
}, {
  slug: 'conference-presentation', title: 'Conference Presentation', subtitle: 'Space for speakers and ideas', location: 'Uganda', category: 'Conferences', categories: ['Conferences','LED & AV','Branding','Rentals'],
  services: ['Conference staging','Presentation screen','Panel furniture','Podium'], images: ['conference'],
  description: 'Panel seating, a presentation screen and a podium frame the conference stage.',
  note: 'A considered stage layout gives each speaker a clear place in the programme.',
}, {
  slug: 'paediatric-conference', title: 'Paediatric Conference', subtitle: 'A platform for the conversation', location: 'Uganda', category: 'Conferences', categories: ['Conferences','LED & AV','Branding','Rentals'],
  services: ['LED backdrop','Panel seating','Podium branding'], images: ['paediatric'],
  description: 'A branded digital backdrop connects the conference identity with the stage, panel seating and speaker podium.',
  note: 'The production supports presentations and panel conversations in a single event environment.',
}];
export const experiences = [['Conferences','conference-production'],['Corporate Events','technical-production'],['Concerts','concerts-live-events'],['Weddings','weddings'],['Nightlife','nightlife'],['Private Events','weddings'],['Brand Activations','event-branding-signage'],['Special Productions','technical-production']];
export const processSteps = [
  { title: 'Understand', line: 'Start with the space.', detail: 'We understand the venue, the audience, the programme and what the event needs to achieve.' },
  { title: 'Design', line: 'Give the idea a shape.', detail: 'Floor plans, guest journeys and stage concepts turn the brief into a clear design direction.' },
  { title: 'Visualise', line: 'See the complete picture.', detail: '3D impressions and walkthroughs help you review the layout and atmosphere before the build.' },
  { title: 'Engineer', line: 'Make every part work together.', detail: 'Sound, lighting, LED, power, staging and rigging are planned as one complete production.' },
  { title: 'Produce', line: 'Build it. Run it. Deliver it.', detail: 'The crew coordinates the setup, rehearsals and show around the approved plan.' },
];
// One furnished 3D model and camera, rendered as a design study and final visualization.
const designImage = (name,alt) => ({ src: '/images/design/'+name+'-1600.webp', srcSet: [480,800,1600].map(w=>'/images/design/'+name+'-'+w+'.webp '+w+'w').join(', '), width: 1600, height: 960, alt });
export const conceptPair = {
  before: designImage('event-wireframe','Wireframe design of a conference event with a stage, truss, screens, lounge sofas, cocktail tables and seating'),
  after: designImage('event-visualised','Finished 3D visualization of the same conference layout with furnished lounges, seating, stage, LED screen and lighting'),
  title: 'Event design and final visualization',
};
export const photoSlots = [['Homepage Hero','stage'],['Conference',null],['Concert',null],['Wedding',null],['Nightlife',null],['LED','installation'],['Audio',null],['Lighting','podium'],['Power / Generator',null],['Trussing',null],['Stage Setup','stage'],['Furniture',null],['Branding / Signage','presentation'],['Team at Work',null],['Office / Ntinda',null],['CEO',null],['3D Design',null],['Concept-to-Reality',null]];
export const aliases = {
  '/design': '/services/event-design-3d-visualisation', '/production': '/services/technical-production',
  '/services/lighting': '/services/event-lighting', '/services/furniture-event-rentals': '/services/event-furniture-rentals',
  '/services/conferences-corporate-events': '/services/conference-production', '/services/concerts-nightlife-live-events': '/services/concerts-live-events',
  ...Object.fromEntries(['after-dark','a-shared-moment','beyond-the-stage','in-the-moment','corporate-summit','wedding-reception'].map(slug=>['/work/'+slug, '/work'])),
};
export const normalisePath = path => { const clean = path.split('?')[0].replace(/\/+$/, '') || '/'; return aliases[clean] || clean; };
export const routes = ['/', '/about', '/services', '/work', '/rentals', '/contact', ...servicePages.map(s=>'/services/'+s.slug), ...projects.map(p=>'/work/'+p.slug)];

// Set a media key here to replace any empty photo slot without editing JSX.
export const slotMedia = {
  "HOMEPAGE HERO": "stage", "TEAM AT WORK": null, "CEO PORTRAIT": null,
  "OFFICE / NTINDA": null, "3D DESIGN": conceptPair.after, "AUDIO SYSTEMS": null,
  "POWER / GENERATOR": null, "TRUSSING & RIGGING": null, "FURNITURE & RENTALS": null,
  "CONFERENCE": "conference", "CONFERENCES": "conference", "CONCERT": null, "CONCERTS": null,
  "WEDDING": null, "WEDDINGS": null, "NIGHTLIFE": null, "PRIVATE EVENTS": null,
  "SPECIAL PRODUCTIONS": null,
};
