export const PHONE = '+256704282211';
export const WHATSAPP = 'https://wa.me/256704282211';
export const services = [
  { title: 'Event Design & 3D Visualisation', short: '3D Design', image: 'planning.png', description: 'See the complete picture. From venue plans and stage concepts to lighting studies and immersive walkthroughs, we give your idea a space to become real.', details: ['Venue & seating plans', 'Stage and set concepts', '3D renders & walkthroughs'] },
  { title: 'Stage & Set Production', short: 'Stage', image: 'live-stage.png', description: 'A stage is the centre of the story. We shape the platforms, scenic elements and custom environments that bring yours into focus.', details: ['Stage design & construction', 'Custom scenic elements', 'Set installation'] },
  { title: 'Lighting Design', short: 'Lighting', image: 'hero.png', description: 'Set the atmosphere. Architectural accents, theatrical looks and carefully timed beams turn the room into part of the performance.', details: ['Lighting concepts', 'Intelligent fixtures', 'Show programming'] },
  { title: 'Audio Visual (AV) Systems', short: 'Audio visual', image: 'conference.png', description: 'Bring sound and picture together. We plan clear audio, confident presentations and bright, well-positioned screens around your venue and audience.', details: ['Professional sound and microphones', 'LED displays and projection', 'Live video, playback and mixing'] },
  { title: 'Event Branding & Signage', short: 'Branding', image: 'branding.png', description: 'Carry your identity through the whole guest journey with considered event graphics, branded environments and clear wayfinding.', details: ['Branded stage backdrops and signage', 'Sponsor and wayfinding displays', 'Environmental graphics for event spaces'] },
  { title: 'Audio Systems', short: 'Audio', image: 'concert.png', description: 'From the first word to the final encore. Audio systems planned for clarity, coverage and the character of your venue.', details: ['Sound system planning', 'Microphones & mixing', 'Live sound support'] },
  { title: 'Trussing & Rigging', short: 'Rigging', image: 'hero.png', description: 'The structure behind the spectacle. Integrated truss layouts and technical planning to support the whole production.', details: ['Truss configuration', 'Technical layouts', 'Production coordination'] },
  { title: 'Conferences & Corporate Events', short: 'Corporate events', image: 'conference.png', description: 'A considered setting for big ideas. Bring your audience, speakers and brand together in a coherent, beautifully produced space.', details: ['Conference environments', 'Brand experiences', 'Speaker & presentation systems'] },
  { title: 'Concerts & Night Experiences', short: 'Live experiences', image: 'crowd.png', description: 'Built for the moment the lights go down. A complete creative and technical approach to live entertainment.', details: ['Concert production', 'Live show design', 'Artist & technical coordination'] },
  { title: 'Furniture & Event Rentals', short: 'Furniture', image: 'reception.png', description: 'The details complete the environment. Build an equipment and furniture brief around the way your event needs to feel and function.', details: ['Event furniture', 'Production equipment', 'Setup & logistics planning'] },
  { title: 'Weddings & Social Events', short: 'Social events', image: 'wedding.png', description: 'A space that feels like you. Thoughtful design, considered lighting and a production plan for your most personal occasions.', details: ['Reception concepts', 'Ambient lighting', 'Furniture & room layouts'] },
];
export const projects = [
  { slug: 'after-dark', title: 'AFTER DARK.', category: 'Live experiences', type: 'Concert concept', image: 'live-stage.png', services: 'STAGE / LIGHTING / LED / AUDIO', description: 'An immersive stage concept where light, sound and a crowd move as one.', brief: 'Create a live environment with a clear focal point, dramatic lighting and a production plan that supports the performance.' },
  { slug: 'a-shared-moment', title: 'A SHARED MOMENT.', category: 'Brand & social', type: 'Social event concept', image: 'experience.png', services: 'EVENT DESIGN / LIGHTING / PRODUCTION', description: 'A warm, expressive setting designed around connection and celebration.', brief: 'Transform an open space into a welcoming social environment, with considered guest flow and a lighting palette that changes through the evening.' },
  { slug: 'beyond-the-stage', title: 'BEYOND THE STAGE.', category: 'Live experiences', type: 'Festival concept', image: 'concert.png', services: 'STAGE / RIGGING / AUDIO / PRODUCTION', description: 'A wide-open canvas for an unforgettable shared experience.', brief: 'Design a large-format live stage with a strong visual identity, clear sightlines and an integrated approach to sound, screens and lighting.' },
  { slug: 'in-the-moment', title: 'IN THE MOMENT.', category: 'Brand & social', type: 'Brand activation concept', image: 'branding.png', services: 'CREATIVE DIRECTION / AV / LIGHTING', description: 'An audience-first experience with a brand at its heart.', brief: 'Build a high-energy environment around a shared moment, using coordinated visuals and lighting to bring the brand story to life.' },
  { slug: 'corporate-summit', title: 'CORPORATE SUMMIT.', category: 'Corporate events', type: 'Conference concept', image: 'conference.png', services: 'SPATIAL DESIGN / LED / AUDIO / PRODUCTION', description: 'A considered environment for big ideas and meaningful conversations.', brief: 'Create an engaging conference environment with clear sightlines, confident presentation systems and an integrated stage design.' },
  { slug: 'wedding-reception', title: 'THE CELEBRATION.', category: 'Weddings', type: 'Wedding concept', image: 'wedding.png', services: 'EVENT DESIGN / LIGHTING / FURNITURE', description: 'A beautifully personal setting for a once-in-a-lifetime moment.', brief: 'Design a warm, elegant reception environment that balances guest comfort, atmosphere and the flow of the celebration.' },
];
export const inventory = [
  { name: 'Moving head beam', category: 'Lighting', kind: 'light', note: 'Focused beams. Big atmosphere.', specs: ['Intelligent lighting', 'Show programming available', 'Indoor & event applications'] },
  { name: 'LED display system', category: 'LED & Display', kind: 'led', note: 'A canvas for your biggest ideas.', specs: ['Modular screen configuration', 'Content playback support', 'Size planned to suit your venue'] },
  { name: 'Line array system', category: 'Audio', kind: 'audio', note: 'Clarity from front to back.', specs: ['Scalable sound coverage', 'Mixing & microphones available', 'Technical support available'] },
  { name: 'Box truss', category: 'Truss & Staging', kind: 'truss', note: 'The structure behind the show.', specs: ['Modular truss layouts', 'Stage & lighting integration', 'Configuration by quotation'] },
  { name: 'Stage platform', category: 'Truss & Staging', kind: 'stage', note: 'Give your moment a platform.', specs: ['Modular stage layouts', 'Venue-specific configurations', 'Installation planning'] },
  { name: 'Modular lounge sofa', category: 'Furniture', kind: 'sofa', note: 'Flexible seating for lounges and VIP spaces.', specs: ['Modular event configurations', 'Social & VIP environments', 'Styles confirmed with your quotation'] },
  { name: 'Conference system', category: 'Conference', kind: 'conference', note: 'Every voice, clearly heard.', specs: ['Presentation & microphone planning', 'Speaker and audience support', 'Technical operator options'] },
  { name: 'Cocktail furniture', category: 'Furniture', kind: 'table', note: 'Designed for conversations.', specs: ['Standing reception layouts', 'Flexible event combinations', 'Quantities confirmed on enquiry'] },
  { name: 'Two-seat event sofa', category: 'Furniture', kind: 'sofa', note: 'Comfortable lounge seating for guests.', specs: ['Reception and lounge seating', 'Pairs with event tables', 'Styles confirmed with your quotation'] },
  { name: 'Accent armchair', category: 'Furniture', kind: 'sofa', note: 'A considered seat for VIP and lounge layouts.', specs: ['Single-seat lounge furniture', 'Combine with sofas and tables', 'Finish confirmed with your quotation'] },
  { name: 'Ottoman lounge seat', category: 'Furniture', kind: 'sofa', note: 'Flexible extra seating for social spaces.', specs: ['Modular lounge arrangements', 'Useful as a footrest or seat', 'Quantities confirmed on enquiry'] },
  { name: 'Event dining chair', category: 'Furniture', kind: 'chair', note: 'Guest seating for dining and reception layouts.', specs: ['Dining and ceremony layouts', 'Pair with event tables', 'Quantities confirmed on enquiry'] },
  { name: 'Banquet table', category: 'Furniture', kind: 'table', note: 'Practical tables for dinners and gatherings.', specs: ['Flexible room configurations', 'Suitable for event seating plans', 'Dimensions confirmed on enquiry'] },
  { name: 'Dance floor', category: 'Staging', kind: 'stage', note: 'A defined space for the celebration.', specs: ['Modular floor layouts', 'Planned around your venue', 'Size confirmed with your quotation'] },
];
export const processSteps = [
  { title: 'Space', line: 'Every great experience starts with an empty space.', detail: 'We understand your venue, your audience and what you want people to feel.' },
  { title: 'Design', line: 'Give the idea a shape.', detail: 'Floor plans, guest journeys and a creative direction turn possibilities into a plan.' },
  { title: 'Visualise', line: 'See the whole picture. Before the first build.', detail: 'Explore stage concepts, seating layouts and the atmosphere in three dimensions.' },
  { title: 'Engineer', line: 'Make every detail work together.', detail: 'Lighting, sound, screens and structure are planned as one complete production.' },
  { title: 'Produce', line: 'From a shared vision to a shared experience.', detail: 'The build, the setup and the show bring the approved concept into the real world.' },
];
